name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Installing Dependencies
        run: npm ci

      - name: Build Application on macOS
        if: matrix.os == 'macos-latest'
        run: |
          npm run build_macos

      - name: Build Application on Windows
        if: matrix.os == 'windows-latest'
        run: |
          npm run build_win

      - name: Build Application on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          npm run build_linux

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: release-builds/